### ISSUE TITLE
Vuforia autonomous Failure to Identify Stopping Point

### ISSUE THREAD

**Issue by BCHSPetersonOwen** [ArkinSolomon/SPQR#2]
Robot does not stop at desired position in autonomous. Possibly not checking correctly, possibly not updating.

**Comment by ArkinSolomon** [comment]
Not checking what correctly? What's not updating? Any LOC where this issue could be occurring.

**Comment by BCHSPetersonOwen** [comment]
@ArkinSolomon not checking its position, think I fixed it.
